# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.1
language: objective-c
# cache: cocoapods
podfile: Example/Podfile
xcode_project: Example/CenteredCollectionView.xcodeproj # path to your xcodeproj folder
xcode_scheme: CenteredCollectionView_Tests
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
# script:
# - set -o pipefail && xcodebuild test -workspace Example/CenteredCollectionView.xcworkspace -scheme CenteredCollectionView-Example -sdk iphonesimulator10.2 -destination 'platform=iOS Simulator,OS=10.2,id=3F31386B-6108-4E3F-BCF7-2A3B0C16AAFE' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
